### ISSUE TITLE
Xkernel on msys2

### ISSUE THREAD

**Issue by typhoon270** [UnfinishedBusiness/Xkernel#1]
hi mate, quick question,

with xkernel windows build instructions, its all pretty simple until the last 3 steps.

PATH=$PATH:/mingw64/bin - i know where that folder is, but doesnt seem to do anything in msys2.
cd /to/Xkernel/ - no matter what directory location i try it wont find the Xkernel file in Xkernel-master directory.
mingw32-make.exe- is this for the makefile in the Xkernel-master folder?

ive been looking for a solution to the gbrl and thc problem for a while, so im stoked to have found your great work and efforts here!

cheers.

**Comment by UnfinishedBusiness** [comment]
Hey @typhoon270,

PATH=$PATH:/mingw64/bin adds the /mingw64/bin directory to the bash path so that mingw64 bins are found (like gcc, g++, mingw32-make, etc) so without adding the /mingw64/bin directory to the path those executables and the glfw dynamic link libraries won't be found. [Check out this link for a detailed explanation on the path environment variable](http://www.linfo.org/path_env_var.html)

The mingw32-make.exe is used and reads the Makefile in the Xkernel repo for building, it's basically a windows port of the linux "make" utility and other make ports don't directly cross over and require a seperate "Windows-Style" Makefile due to path issues such which is why I chose MSYS2 because this way Windows, OSX, and Linux building is all wrapped in the same Makefile this way.

Thanks.

**Comment by typhoon270** [comment]
nothing seems to happen when i enter the PATH=$PATH:/mingw64/bin command, ive tried a few different ways, and gone through the detailed link and tried some of them. here's a screenshot after i uninstalled and went through the steps again:

(1/1) checking for file conflicts                  [#####################] 100%
(1/1) checking available disk space                [#####################] 100%
:: Processing package changes...
(1/1) installing mingw-w64-x86_64-freeglut         [#####################] 100%

mckinnon1@lukes MSYS ~
$ PATH=$PATH:/mingw64/bin

mckinnon1@lukes MSYS ~
$ cd /to/Xkernel/
-bash: cd: /to/Xkernel/: No such file or directory

mckinnon1@lukes MSYS ~
$ /c/Users/mckinnon1/Documents/XmotionFirmware-master/XmotionFirmware-master/Xkernel-master/Xkernel-master
-bash: /c/Users/mckinnon1/Documents/XmotionFirmware-master/XmotionFirmware-master/Xkernel-master/Xkernel-master: Is a directory

mckinnon1@lukes MSYS ~
$ mingw32-make.exe
mingw32-make: *** No targets specified and no makefile found.  Stop.

mckinnon1@lukes MSYS ~
$

thanks for your help its much appreciated!

**Comment by UnfinishedBusiness** [comment]
Hey @typhoon270,

When you update the PATH variable there won't be any output from that command but it is absolutely necessary to do it. You can echo $PATH to see the result of you appending the mingw64 bin folder to it.

What I mean by "cd /to/Xkernel" is change directory to where you cloned the Xkernel repository.

I usually set up my directory structure like the following
/c/Xmotion
/c/Xmotion/Xkernel (This is the cloned Xkernel repository)
/c/Xmotion/ncPilot (This is the cloned ncPilot repository)

Once you have entered the Xkernel repository and have the PATH variable set correctly, you can then use mingw32-make.exe to build Xkernel.

Thanks

**Comment by typhoon270** [comment]
thanks for that, it worked! it built xkernel, we have progress. when i try to open the xkernel application, is says libgcc_s_seh-1.dll is missing from your computer. ive tried editing the enviroment variables to the mingw64/bin folder where all the libgcc files are located, but it doesnt work.
i then copied libgcc_s_seh-1.dll into the xkernel.exe folder, which got rid of that error code, but gave another missing file.

i placed all the missing files in the .exe folder, and thats where im at.

sorry for all the questins and problems!  thanks

![Screenshot (38)](https://user-images.githubusercontent.com/62824721/77975982-6ace5200-7347-11ea-9cbb-af8d0c91e044.png)

**Comment by UnfinishedBusiness** [comment]
Hey @typhoon270,

No worries about all the questions, there’s very little documentation right now and I appreciate your perseverance. 

I haven’t experienced that about it not finding the dll files once the PATH variable is set but none the less, your solution is perfectly fine.

So if you just execute Xkernel without any arguments that’s exactly what it will say right now... you’ve successfully compiled it and I should add a help output in the near future when no arguments are supplied so avoid an exception.

So if you create a JavaScript file called test.js like the following (notice it looks like Arduino code)
```
function setup()
{
 print(“setup\n”);
}
function loop()
{
print(“looping\n”);
}
```
Then run ./Xkernel test.js

You’ll see one setup printout then a bunch of loops until you terminate it. That means is executing the JavaScript code.

Now if you clone the ncPilot repository you can run ncPilot program (which is written entirely in my Xkernel flavored JavaScript language) with Xkernel. In ncPilot the arc/main.js is the entry point

So change directory to ncPilot repo
Then ../Xkernel/Xkernel arc/main.js 

That assumes the directory hierarchy that I specified in my last message

Thanks

**Comment by typhoon270** [comment]
alright, ive got the test.js looping in the msys2 no problem, with the cloning of the ncpilot repo, am i cloning that into the xkernel directory?. 

thanks

![Screenshot (39)](https://user-images.githubusercontent.com/62824721/77989497-b3e3cd80-736a-11ea-861b-a90aa7197a96.png)
![Screenshot (40)](https://user-images.githubusercontent.com/62824721/77989514-bb0adb80-736a-11ea-8e6e-71d069f873fe.png)

**Comment by UnfinishedBusiness** [comment]
@typhoon270 - Did you get things up and running okay?
