### ISSUE TITLE
glfw and glew don't seem to be available for ubuntu 19.10.

### ISSUE THREAD

**Issue by moose4621** [UnfinishedBusiness/Xkernel#2]
I am keen to try your THC version of GRBL as I have been running GRBL std on a plasma for a few years without any THC. Time to move forward.
I am trying to install Xkernel in Ubuntu 19.10 but I keep getting dependency problems. For example glfw-dev and glew-dev are not available via official repos, and after downloading glfw from their site, it seems running X11 is a requirement which ubuntu 19.10 will not allow installed.

Any assistance for installing in ubuntu 19.10 or later would be appreciated.
Thanks, Chris

**Comment by UnfinishedBusiness** [comment]
Hey Chris,

Sounds great! Glad you came across my project.

It should build fine in Ubuntu but I have not tried it. I have installed it on Debian though.

Have you installed libglfw-dev package using apt-get?

**Comment by moose4621** [comment]
Thanks for the reply.
I have managed to install libglfw3-dev and libglew-dev and a successful make of Xkernel.
My problem now is with ncPilot. When I run "js main.js /dev/ttyUSB0" in terminal I get 
"internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/home/chris/Xmotion/ncPilot/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
"
I have placed the ncPilot dir in the Xmotion dir which is in my home dir. Is that right?

What am I missing?

**Comment by moose4621** [comment]
Never mind, I finally worked it out. Doh!
Interface is up. Looks ok.
I am keen now to alter the hardware to get this going.

Thanks for your effort and for sharing.

**Comment by UnfinishedBusiness** [comment]
Excellent! Glad you got everything sorted out. Feel free to reach out for help with any other problems you may come across

Thanks,
Travis
